# Sudoku Solver - Using the Crosshatching Method

In [1]:
import numpy as np

In [2]:
grid = np.zeros((9,9), dtype=np.int64)
grid

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

## Create sample Sudoku puzzle

In [3]:
a = np.array([0,0,2,4,0,0,0,3,9]).reshape((3,3))
b = np.array([9,8,0,0,7,0,6,0,4]).reshape((3,3))
c = np.array([5,0,0,0,1,3,0,7,0]).reshape((3,3))
d = np.array([2,0,0,8,4,0,9,0,7]).reshape((3,3))
e = np.array([0,5,6,3,0,0,0,0,1]).reshape((3,3))
f = np.array([4,0,0,2,0,1,0,8,6]).reshape((3,3))
g = np.array([6,0,0,0,9,1,0,2,0]).reshape((3,3))
h = np.array([7,0,5,4,0,0,0,3,0]).reshape((3,3))
i = np.array([1,3,0,0,0,5,6,0,8]).reshape((3,3))

#### Function to Concatenate the sub-grids into 1 large 9x9 grid
np.concatenate((array1, array2), axis=1) <br> 
- Concatenates to the side (column wise) with axis=1
- Concatenates down (row wise) with axis=0

In [4]:
def set_grid(a,b,c,d,e,f,g,h,i):
    row1 = np.concatenate((a, b, c), axis=1)
    row2 = np.concatenate((d, e, f), axis=1)
    row3 = np.concatenate((g, h, i), axis=1)
    grid = np.concatenate((row1, row2, row3), axis=0)
    return grid

Same as above in 1 line

In [5]:
def set_grid2(a,b,c,d,e,f,g,h,i):
    grid = np.concatenate( (np.concatenate((a, b, c), axis=1), np.concatenate((d, e, f), axis=1), np.concatenate((g, h, i), axis=1)), axis=0 )
    return grid

In [6]:
grid = set_grid(a,b,c,d,e,f,g,h,i)
grid

array([[0, 0, 2, 9, 8, 0, 5, 0, 0],
       [4, 0, 0, 0, 7, 0, 0, 1, 3],
       [0, 3, 9, 6, 0, 4, 0, 7, 0],
       [2, 0, 0, 0, 5, 6, 4, 0, 0],
       [8, 4, 0, 3, 0, 0, 2, 0, 1],
       [9, 0, 7, 0, 0, 1, 0, 8, 6],
       [6, 0, 0, 7, 0, 5, 1, 3, 0],
       [0, 9, 1, 4, 0, 0, 0, 0, 5],
       [0, 2, 0, 0, 3, 0, 6, 0, 8]])

## Find all possible numbers for each sub-grid
#### Using numpy.setdiff1d(array1, array2) - Return the sorted, unique values in array1 that are not in array2 (Order matters)

In [7]:
choice = np.setdiff1d(np.arange(10), a)
choice

array([1, 5, 6, 7, 8])

#### Convert array of possible choices into a single number

In [8]:
choice = int(''.join(str(x) for x in choice))
choice

15678

## Assign the possible choice to all empty spots in the appropriate sub-grid

#### Use mask to assign zeros to the possible choice variable

In [9]:
a[a == 0] = choice
a

array([[15678, 15678,     2],
       [    4, 15678, 15678],
       [15678,     3,     9]])

In [10]:
grid = set_grid(a,b,c,d,e,f,g,h,i)
grid

array([[15678, 15678,     2,     9,     8,     0,     5,     0,     0],
       [    4, 15678, 15678,     0,     7,     0,     0,     1,     3],
       [15678,     3,     9,     6,     0,     4,     0,     7,     0],
       [    2,     0,     0,     0,     5,     6,     4,     0,     0],
       [    8,     4,     0,     3,     0,     0,     2,     0,     1],
       [    9,     0,     7,     0,     0,     1,     0,     8,     6],
       [    6,     0,     0,     7,     0,     5,     1,     3,     0],
       [    0,     9,     1,     4,     0,     0,     0,     0,     5],
       [    0,     2,     0,     0,     3,     0,     6,     0,     8]])

## For each unassigned element in the sub-grid, eliminate the numbers in its row and column from the pool of possible numbers

In [13]:
grid_length = grid.shape[0]
for x in range(grid_length):
    for y in range(grid_length):
        #if element is longer than 1 digit check its row and column
        if (len(str(grid[x,y])) > 1 ): 
            print(grid[x,y])

15678
15678
15678
15678
15678
