# NumPy Sudoku Solver

In [29]:
import numpy as np

### Create a 3x3 matrix

In [30]:
grid = np.zeros((3,3), dtype=np.int64)
grid

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

### Create a Function to fill an Array of given length with unique Random Numbers by row

In [31]:
def set_random(cube):
    
    cube_length = cube.shape[0]
    for x in range(cube_length):
        cube[x,:] = np.random.choice(range(1,(cube_length + 1)), cube_length, replace=False)
    
    return cube 


### Seed with Random numbers

In [35]:
set_random(grid)

array([[2, 1, 3],
       [2, 1, 3],
       [1, 2, 3]], dtype=int64)

### Create a function to check if any numbers repeat in a given column

In [36]:
def check_cube(cube):
    cube_length = cube.shape[0]
    
    check = True

    for x in range(cube_length - 1):
        for y in range(cube_length):
            #if first element in in the rest of the column
            if ( cube[x,y] in cube[(x+1):, y] ):
                check = False
                return check
            else: 
                check = True
                
    return check


### Generate a random matrix with unique columns

In [37]:
check = check_cube(grid)
while check == False:
    set_random(grid)
    check = check_cube(grid)
grid

array([[2, 1, 3],
       [1, 3, 2],
       [3, 2, 1]], dtype=int64)