# NumPy Sudoku Solver

In [1]:
import numpy as np

### Create a 3x3 matrix

In [2]:
grid = np.zeros((4,4), dtype=np.int64)
grid

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [3]:
grid.shape

(4, 4)

### Create a Function to fill an Array of given length with unique Random Numbers by row

#### Using np.random.choice(a, size=None, replace=True) 
- a: 1D Array or range <br>
- size: how many numbers to generate <br>
- replace: False to generate only unique numbers

In [4]:
def set_random(arr):
    
    arr_length = arr.shape[0]
    for x in range(arr_length): #for each row
        arr[x,:] = np.random.choice(range(1,(arr_length + 1)), arr_length, replace=False)
    
    return arr 


### Seed with Random numbers

In [5]:
#%%timeit
set_random(grid)

array([[4, 2, 1, 3],
       [3, 2, 1, 4],
       [4, 3, 1, 2],
       [3, 4, 1, 2]], dtype=int64)

## Create a function to check if any numbers repeat in a given column

#### Python way with loops - Returns True if all unique, returns False if numbers are repeated

In [6]:
def check_arr1(arr):
    arr_length = arr.shape[0]
    
    check = True

    for x in range(arr_length - 1):
        for y in range(arr_length):
            #if first element in in the rest of the column
            if ( arr[x,y] in arr[(x+1):, y] ): #arr[0,0] in arr[1:,0]
                check = False
                return check #if check is False, return out of function 
            else: 
                check = True
                
    return check


#### NumPy way with loops - Returns True if all unique.  Returns False if numbers are repeated
Check to see if number of unique elements in a column is equal to the size of the column. <br>
- np.unique(arr) return another array of just unique values
- np.unique([1, 1, 2, 2, 3, 3]) returns [1, 2, 3]

In [7]:
def check_arr2(arr):
    for i in range(arr.shape[1]):
        #unique numbers in all rows of column i
        if np.unique(arr[:, i]).size < arr.shape[0]:
            return False
    return True

#### NumPy way with no loops
Sort array by column (axis=0). Check whether there are two or more equal values next to each other (non-unique values in a sorted array) by comparing their difference to 0

In [8]:
def check_arr3(arr):
    if ( np.any(np.diff(np.sort(arr, axis=0), axis=0) == 0) ):
        return False
    return True

## Generating the Grids 

In [9]:
grid = np.zeros((4,4), dtype=np.int64)
set_random(grid)


array([[4, 2, 1, 3],
       [3, 1, 4, 2],
       [1, 3, 2, 4],
       [4, 3, 1, 2]], dtype=int64)

#### Using Python way with loops - Using while loop untill check is True (all unique)

In [10]:
#%%timeit
grid = np.zeros((4,4), dtype=np.int64)
set_random(grid)
check = check_arr1(grid)
while check == False:
    set_random(grid)
    check = check_arr1(grid)
grid

array([[3, 4, 1, 2],
       [4, 3, 2, 1],
       [1, 2, 4, 3],
       [2, 1, 3, 4]], dtype=int64)

#### Using Numpy way with loops - Using while loop untill check is True (all unique)

In [11]:
#%%timeit
grid = np.zeros((4,4), dtype=np.int64)
set_random(grid)
check = check_arr2(grid)
while check == False:
    set_random(grid)
    check = check_arr2(grid)
grid

array([[4, 3, 1, 2],
       [2, 1, 3, 4],
       [1, 2, 4, 3],
       [3, 4, 2, 1]], dtype=int64)

#### Using Numpy way with no loops

In [12]:
#%%timeit
grid = np.zeros((4,4), dtype=np.int64)
set_random(grid)
check = check_arr3(grid)
while check == False:
    set_random(grid)
    check = check_arr3(grid)
grid

array([[3, 4, 1, 2],
       [4, 3, 2, 1],
       [1, 2, 3, 4],
       [2, 1, 4, 3]], dtype=int64)