# NumPy Sudoku Solver

In [1]:
import numpy as np

### Create a 3x3 matrix

In [2]:
grid = np.zeros((4,4), dtype=np.int64)
grid

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

### Create a Function to fill an Array of given length with unique Random Numbers by row

In [3]:
def set_random(arr):
    
    arr_length = arr.shape[0]
    for x in range(arr_length):
        arr[x,:] = np.random.choice(range(1,(arr_length + 1)), arr_length, replace=False)
    
    return arr 


### Seed with Random numbers

In [4]:
set_random(grid)

array([[4, 2, 3, 1],
       [1, 3, 4, 2],
       [3, 4, 1, 2],
       [1, 4, 2, 3]], dtype=int64)

## Create a function to check if any numbers repeat in a given column

#### Python way with loops

In [5]:
def check_arr1(cube):
    cube_length = cube.shape[0]
    
    check = True

    for x in range(cube_length - 1):
        for y in range(cube_length):
            #if first element in in the rest of the column
            if ( cube[x,y] in cube[(x+1):, y] ):
                check = False
                return check
            else: 
                check = True
                
    return check


#### NumPy way with loops
Check to see if number of unique elements in a column is equal to the size of the column.  Returns True if all unique.  Returns False if contains duplicates

In [6]:
def check_arr2(arr):
    for i in range(arr.shape[1]):
        if np.unique(arr[:, i]).size < arr.shape[0]:
            return False
    return True

#### NumPy way with no loops
Sort array by column (axis=0). Check whether there are two or more equal values next to each other (non-unique values in a sorted array) by comparing their difference to 0

In [7]:
def check_arr3(arr):
    if ( np.any(np.diff(np.sort(arr, axis=0), axis=0) == 0) ):
        return False
    return True

## Generating the Grids 

#### Using Python way with loops

In [8]:
#%%timeit
grid = np.zeros((4,4), dtype=np.int64)
set_random(grid)
check = check_arr1(grid)
while check == False:
    set_random(grid)
    check = check_arr1(grid)
grid

array([[4, 2, 1, 3],
       [1, 3, 4, 2],
       [2, 1, 3, 4],
       [3, 4, 2, 1]], dtype=int64)

#### Using Numpy way with loops

In [9]:
#%%timeit
grid = np.zeros((4,4), dtype=np.int64)
set_random(grid)
check = check_arr2(grid)
while check == False:
    set_random(grid)
    check = check_arr2(grid)
grid

array([[1, 4, 3, 2],
       [4, 1, 2, 3],
       [2, 3, 4, 1],
       [3, 2, 1, 4]], dtype=int64)

#### Using Numpy way with no loops

In [10]:
#%%timeit
grid = np.zeros((4,4), dtype=np.int64)
set_random(grid)
check = check_arr3(grid)
while check == False:
    set_random(grid)
    check = check_arr3(grid)
grid

array([[1, 4, 2, 3],
       [4, 1, 3, 2],
       [2, 3, 4, 1],
       [3, 2, 1, 4]], dtype=int64)