# Sudoku Solver - Using the Crosshatching Method

In [58]:
import numpy as np

In [59]:
grid = np.zeros((9,9), dtype=np.int64)
grid

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

## Create sample Sudoku puzzle

In [60]:
a = np.array([0,0,2,4,0,0,0,3,9]).reshape((3,3))
b = np.array([9,8,0,0,7,0,6,0,4]).reshape((3,3))
c = np.array([5,0,0,0,1,3,0,7,0]).reshape((3,3))
d = np.array([2,0,0,8,4,0,9,0,7]).reshape((3,3))
e = np.array([0,5,6,3,0,0,0,0,1]).reshape((3,3))
f = np.array([4,0,0,2,0,1,0,8,6]).reshape((3,3))
g = np.array([6,0,0,0,9,1,0,2,0]).reshape((3,3))
h = np.array([7,0,5,4,0,0,0,3,0]).reshape((3,3))
i = np.array([1,3,0,0,0,5,6,0,8]).reshape((3,3))

#### Function to Concatenate the sub-grids into 1 large 9x9 grid
np.concatenate((array1, array2), axis=1) <br> 
- Concatenates to the side (column wise) with axis=1
- Concatenates down (row wise) with axis=0

In [61]:
def set_grid(a,b,c,d,e,f,g,h,i):
    row1 = np.concatenate((a, b, c), axis=1) #axis=1 column wise
    row2 = np.concatenate((d, e, f), axis=1)
    row3 = np.concatenate((g, h, i), axis=1)
    grid = np.concatenate((row1, row2, row3), axis=0) #axis=0 row wise
    return grid

Same as above in 1 line

In [62]:
def set_grid2(a,b,c,d,e,f,g,h,i):
    grid = np.concatenate( (np.concatenate((a, b, c), axis=1), np.concatenate((d, e, f), axis=1), np.concatenate((g, h, i), axis=1)), axis=0 )
    return grid

In [63]:
grid = set_grid(a,b,c,d,e,f,g,h,i)
grid

array([[0, 0, 2, 9, 8, 0, 5, 0, 0],
       [4, 0, 0, 0, 7, 0, 0, 1, 3],
       [0, 3, 9, 6, 0, 4, 0, 7, 0],
       [2, 0, 0, 0, 5, 6, 4, 0, 0],
       [8, 4, 0, 3, 0, 0, 2, 0, 1],
       [9, 0, 7, 0, 0, 1, 0, 8, 6],
       [6, 0, 0, 7, 0, 5, 1, 3, 0],
       [0, 9, 1, 4, 0, 0, 0, 0, 5],
       [0, 2, 0, 0, 3, 0, 6, 0, 8]])

## Set sub-grids to be view of the main grid

In [64]:
a = grid[0:3, 0:3]
b = grid[0:3, 3:6]
c = grid[0:3, 6:9]
d = grid[3:6, 0:3]
e = grid[3:6, 3:6]
f = grid[3:6, 6:9]
g = grid[6:9, 0:3]
h = grid[6:9, 3:6]
i = grid[6:9, 6:9]

## Find all possible numbers for each sub-grid
#### Using numpy.setdiff1d(array1, array2) - Return the sorted, unique values in array1 that are not in array2 (Order matters)

In [65]:
choice = np.setdiff1d(np.arange(1,10), a)
choice

array([1, 5, 6, 7, 8])

#### Convert array of possible choices into a single number

In [66]:
choice = int(''.join(str(x) for x in choice))
choice

15678

## Assign the possible choice to all empty spots in the appropriate sub-grid

#### Use mask to assign zeros to the possible choice variable

In [67]:
a[a == 0] = choice
a

array([[15678, 15678,     2],
       [    4, 15678, 15678],
       [15678,     3,     9]])

In [68]:
grid = set_grid(a,b,c,d,e,f,g,h,i)
grid

array([[15678, 15678,     2,     9,     8,     0,     5,     0,     0],
       [    4, 15678, 15678,     0,     7,     0,     0,     1,     3],
       [15678,     3,     9,     6,     0,     4,     0,     7,     0],
       [    2,     0,     0,     0,     5,     6,     4,     0,     0],
       [    8,     4,     0,     3,     0,     0,     2,     0,     1],
       [    9,     0,     7,     0,     0,     1,     0,     8,     6],
       [    6,     0,     0,     7,     0,     5,     1,     3,     0],
       [    0,     9,     1,     4,     0,     0,     0,     0,     5],
       [    0,     2,     0,     0,     3,     0,     6,     0,     8]])

## Eliminate the numbers in the row and column from the pool of possible numbers

In [91]:
arr = np.empty(0, dtype=np.int64)
print(arr)
grid_length = grid.shape[0]
for x in range(grid_length): #row
    for y in range(grid_length): #column
        #if element is longer than 1 digit check its row and column
        if (len(str(grid[x,y])) > 1 ): 
            print(grid[x, :])
            print(grid[:, y])
            arr = np.append(arr, grid[x, :])
            arr = np.append(arr, grid[:, y])
            print("arr: ", arr)
            arr = arr[ len(str(a)) == 1]
            print("arr modified: ", arr)
        

[]
[15678 15678     2     9     8     0     5     0     0]
[15678     4 15678     2     8     9     6     0     0]
arr:  [15678 15678     2     9     8     0     5     0     0 15678     4 15678
     2     8     9     6     0     0]
arr modified:  15678
[15678 15678     2     9     8     0     5     0     0]
[15678 15678     3     0     4     0     0     9     2]
arr:  [15678 15678 15678     2     9     8     0     5     0     0 15678 15678
     3     0     4     0     0     9     2]
arr modified:  15678
[    4 15678 15678     0     7     0     0     1     3]
[15678 15678     3     0     4     0     0     9     2]
arr:  [15678     4 15678 15678     0     7     0     0     1     3 15678 15678
     3     0     4     0     0     9     2]
arr modified:  15678
[    4 15678 15678     0     7     0     0     1     3]
[    2 15678     9     0     0     7     0     1     0]
arr:  [15678     4 15678 15678     0     7     0     0     1     3     2 15678
     9     0     0     7     0     1     0]


C:\Users\10138050\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\__main__.py:13: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
