# Sudoku Solver - Using the Crosshatching Method

In [1]:
import numpy as np

In [2]:
grid = np.zeros((9,9), dtype=np.int64)
grid

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

## Create sample Sudoku puzzle

#### Easy puzzle

a = np.array([0,0,2,4,0,0,0,3,9]).reshape((3,3))
b = np.array([9,8,0,0,7,0,6,0,4]).reshape((3,3))
c = np.array([5,0,0,0,1,3,0,7,0]).reshape((3,3))
d = np.array([2,0,0,8,4,0,9,0,7]).reshape((3,3))
e = np.array([0,5,6,3,0,0,0,0,1]).reshape((3,3))
f = np.array([4,0,0,2,0,1,0,8,6]).reshape((3,3))
g = np.array([6,0,0,0,9,1,0,2,0]).reshape((3,3))
h = np.array([7,0,5,4,0,0,0,3,0]).reshape((3,3))
i = np.array([1,3,0,0,0,5,6,0,8]).reshape((3,3))

#### Easy puzzle

a = np.array([0,0,0,6,8,0,1,9,0]).reshape((3,3))
b = np.array([2,6,0,0,7,0,0,0,4]).reshape((3,3))
c = np.array([7,0,1,0,9,0,5,0,0]).reshape((3,3))
d = np.array([8,2,0,0,0,4,0,5,0]).reshape((3,3))
e = np.array([1,0,0,6,0,2,0,0,3]).reshape((3,3))
f = np.array([0,4,0,9,0,0,0,2,8]).reshape((3,3))
g = np.array([0,0,9,0,4,0,7,0,3]).reshape((3,3))
h = np.array([3,0,0,0,5,0,0,1,8]).reshape((3,3))
i = np.array([0,7,4,0,3,6,0,0,0]).reshape((3,3))

#### Eazy puzzle

In [3]:
a = np.array([1,0,0,7,3,0,0,0,0]).reshape((3,3))
b = np.array([4,8,9,0,0,0,0,0,1]).reshape((3,3))
c = np.array([0,0,6,0,4,0,2,9,5]).reshape((3,3))
d = np.array([0,0,7,5,0,0,0,0,6]).reshape((3,3))
e = np.array([1,2,0,7,0,3,0,9,5]).reshape((3,3))
f = np.array([6,0,0,0,0,8,7,0,0]).reshape((3,3))
g = np.array([9,1,4,0,2,0,8,0,0]).reshape((3,3))
h = np.array([6,0,0,0,0,0,5,1,2]).reshape((3,3))
i = np.array([0,0,0,0,3,7,0,0,4]).reshape((3,3))

#### Intermediate puzzle

a = np.array([0,2,0,5,8,0,0,0,0]).reshape((3,3))
b = np.array([6,0,8,0,0,9,0,4,0]).reshape((3,3))
c = np.array([0,0,0,7,0,0,0,0,0]).reshape((3,3))
d = np.array([3,7,0,6,0,0,0,0,8]).reshape((3,3))
e = np.array([0,0,0,0,0,0,0,0,0]).reshape((3,3))
f = np.array([5,0,0,0,0,4,0,1,3]).reshape((3,3))
g = np.array([0,0,0,0,0,9,0,0,0]).reshape((3,3))
h = np.array([0,2,0,8,0,0,3,0,6]).reshape((3,3))
i = np.array([0,0,0,0,3,6,0,9,0]).reshape((3,3))

#### Hard puzzle

a = np.array([0,2,0,0,0,0,0,7,4]).reshape((3,3))
b = np.array([0,0,0,6,0,0,0,8,0]).reshape((3,3))
c = np.array([0,0,0,0,0,3,0,0,0]).reshape((3,3))
d = np.array([0,0,0,0,8,0,6,0,0]).reshape((3,3))
e = np.array([0,0,3,0,4,0,5,0,0]).reshape((3,3))
f = np.array([0,0,2,0,1,0,0,0,0]).reshape((3,3))
g = np.array([0,0,0,5,0,0,0,0,0]).reshape((3,3))
h = np.array([0,1,0,0,0,9,0,0,0]).reshape((3,3))
i = np.array([7,8,0,0,0,0,0,4,0]).reshape((3,3))

#### Function to Concatenate the sub-grids into 1 large 9x9 grid
np.concatenate((array1, array2), axis=1) <br> 
- Concatenates to the side (column wise) with axis=1
- Concatenates down (row wise) with axis=0

In [4]:
def set_grid(a,b,c,d,e,f,g,h,i):
    row1 = np.concatenate((a, b, c), axis=1) #axis=1 column wise
    row2 = np.concatenate((d, e, f), axis=1)
    row3 = np.concatenate((g, h, i), axis=1)
    grid = np.concatenate((row1, row2, row3), axis=0) #axis=0 row wise
    return grid

Same as above in 1 line

In [5]:
def set_grid2(a,b,c,d,e,f,g,h,i):
    grid = np.concatenate( (np.concatenate((a, b, c), axis=1), np.concatenate((d, e, f), axis=1), np.concatenate((g, h, i), axis=1)), axis=0 )
    return grid

In [6]:
grid = set_grid(a,b,c,d,e,f,g,h,i)
grid

array([[1, 0, 0, 4, 8, 9, 0, 0, 6],
       [7, 3, 0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 1, 2, 9, 5],
       [0, 0, 7, 1, 2, 0, 6, 0, 0],
       [5, 0, 0, 7, 0, 3, 0, 0, 8],
       [0, 0, 6, 0, 9, 5, 7, 0, 0],
       [9, 1, 4, 6, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 3, 7],
       [8, 0, 0, 5, 1, 2, 0, 0, 4]])

## Set sub-grids to be view of the main grid

In [7]:
a = grid[0:3, 0:3]
b = grid[0:3, 3:6]
c = grid[0:3, 6:9]
d = grid[3:6, 0:3]
e = grid[3:6, 3:6]
f = grid[3:6, 6:9]
g = grid[6:9, 0:3]
h = grid[6:9, 3:6]
i = grid[6:9, 6:9]

In [8]:
subGrids = [a,b,c,d,e,f,g,h,i]
#subGrids

## Function to find all possible numbers for each sub-grid
- Using numpy.setdiff1d(array1, array2) - Return the sorted, unique values in array1 that are not in array2 (Order matters)
- Convert array of possible choices into a single number

In [9]:
def possibleEntry(arr2, arr1=np.arange(1,10)):
    if(len(arr1) == 0): #if comparing array is empty, just return the other array
        return arr2
    else:
        choice = np.setdiff1d(arr1, arr2)
        if(len(choice) > 0): #if not empty join into a single number
            choice = int(''.join(str(i) for i in choice))
            return choice
        else: #if empty, return empty array
            return choice

## Assign the possible choice to all empty spots in the appropriate sub-grid

#### Use mask to assign zeros to the possible choice variable

In [10]:
#a[a == 0] = possibleEntry(a)
#a

In [11]:
#grid = set_grid(a,b,c,d,e,f,g,h,i)
#grid

## Eliminate the numbers in the row and column from the pool of possible numbers

In [12]:
def crosshatch(grid):
    #set array to add possible numbers to, based on row and column
    pool = np.empty(0, dtype=np.int64)
    
    grid_length = grid.shape[0]
    for x in range(grid_length): #row
        for y in range(grid_length): #column
            #if element is longer than 1 digit check its row and column
            if (len(str(grid[x,y])) > 1 ): 

                pool = np.append(pool, grid[x, :]) #append all the numbers in that element's row
                pool = np.append(pool, grid[:, y]) #append all the numbers in that element's column
                pool = pool[ pool < 10] #eliminate any number laster than 9

                current = [int(i) for i in str(grid[x,y])] #convert current element into an array of numbers
                np.asarray(current, dtype=np.int64)
            
                #assign the element to a new possibleEntry
                grid[x,y] = possibleEntry(pool, current)
            
                #reset the pool for the next element
                pool = np.empty(0, dtype=np.int64)
    
    return grid
            
        

In [13]:
crosshatch(grid)

array([[1, 0, 0, 4, 8, 9, 0, 0, 6],
       [7, 3, 0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 1, 2, 9, 5],
       [0, 0, 7, 1, 2, 0, 6, 0, 0],
       [5, 0, 0, 7, 0, 3, 0, 0, 8],
       [0, 0, 6, 0, 9, 5, 7, 0, 0],
       [9, 1, 4, 6, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 3, 7],
       [8, 0, 0, 5, 1, 2, 0, 0, 4]])

## Function to check if puzzle is complete

#### Returns False if grid contains zeros or numbers larger than 9

In [14]:
def checkGrid(grid):
    grid_length = grid.shape[0]
    for x in range(grid_length): #row
        for y in range(grid_length): #column
            if (grid[x,y] > 9 or int(grid[x,y]) == 0):
                return False
    return True
    

In [15]:
while checkGrid(grid) == False:
    for i in subGrids:
        i[i == 0] = possibleEntry(i)
        crosshatch(grid)

In [16]:
grid

array([[1, 5, 2, 4, 8, 9, 3, 7, 6],
       [7, 3, 9, 2, 5, 6, 8, 4, 1],
       [4, 6, 8, 3, 7, 1, 2, 9, 5],
       [3, 8, 7, 1, 2, 4, 6, 5, 9],
       [5, 9, 1, 7, 6, 3, 4, 2, 8],
       [2, 4, 6, 8, 9, 5, 7, 1, 3],
       [9, 1, 4, 6, 3, 7, 5, 8, 2],
       [6, 2, 5, 9, 4, 8, 1, 3, 7],
       [8, 7, 3, 5, 1, 2, 9, 6, 4]])